name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        docker pull verilator/verilator
        FILE=uart
        FILES=$(ls *.v | sed s/${FILE}\.\v//)
        echo FILE=$FILE FILES=$FILES
        docker run --rm --log-driver=none -a stdout -a stderr -w/work -v${PWD}/:/work verilator/verilator -Wall -Wno-UNUSED --top-module $FILE --lint-only $FILE.v $FILES
