name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        docker pull verilator/verilator
        FILE=top
        FILES=$(ls *.v | sed s/${FILE}\.\v//)
        docker run --rm \
          --log-driver=none -a stdout -a stderr \
          -w/work -v${PWD}/:/work \
          --entrypoint /usr/local/bin/verilator \
          verilator/verilator \
          -Wall -Wno-UNUSED --lint-only --top-module $FILE $FILE.v $FILES
