name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a multi-line script
      run: |
        docker pull verilator/verilator
        FILE=uart
        FILES=$(ls *.v | sed s/${FILE}\.\v//)
        echo FILE=$FILE FILES=$FILES
        echo "PWD IS"
        pwd
        echo "FIND ."
        find .
        echo "DoCKER IMAGES"
        docker images
        echo "DoCKER RUN"
        docker run --rm --log-driver=none -a stdout -a stderr -w/work -v${PWD}/:/work verilator/verilator -Wall -Wno-UNUSED --top-module --lint-only $FILE $FILE.v $FILES
